gx.setStaticDirectory(gx.text.chr(47));
gx.setBlankWhenEmptyDate( false );

gx.gxBuild =  1910300 ;
gx.gen.net = true;
gx.setLanguageCode( 'eng' );
gx.setDateFormat( "MDY" );
gx.setTimeFormat( 12 );
gx.setCenturyFirstYear( 40 );
gx.setDecimalPoint( '.' );
gx.setThousandSeparator( ',' );
gx.TabOnPrompSelect =  false ;
gx.StorageTimeZone =  1 ;
gx.datepickerImage=[];
gx.blankImage="blank.jpg";
gx.ascImage="asc.gif";
gx.descImage="desc.gif";
gx.expandImage="expand.gif";
gx.collapseImage="collapse.gif";
gx.downloadImage="download.gif";
gx.indicatorImage="indicator.gif";
gx.promptImage="prompt.gif";
gx.myLocationImage="locateMe.gif";
gx.resizeImage="resize.gif";
gx.csv.stopOnError = false;
gx.csv.dismissSeconds = 0;
gx.csv.messagePosition =  "right" ;
gx.csv.overlap = true;
gx.csv.oneAtAtime = true;
gx.HTML5 = true;
